"""add refresh_id to login_sessions

Revision ID: 5e31bcaf0cf4
Revises: 609c11174142
Create Date: 2026-07-05 15:44:42.145603

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e31bcaf0cf4"  # pragma: allowlist secret
down_revision: Union[str, None] = "609c11174142"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "login_sessions", sa.Column("refresh_id", sa.String(length=64), nullable=True)
    )
    op.create_index(
        op.f("ix_login_sessions_refresh_id"),
        "login_sessions",
        ["refresh_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_login_sessions_refresh_id"), table_name="login_sessions")
    op.drop_column("login_sessions", "refresh_id")
    # ### end Alembic commands ###
