"""baseline current schema

Revision ID: 609c11174142
Revises:
Create Date: 2026-07-05 09:33:25.674304

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "609c11174142"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mfa_challenges_created_at", table_name="mfa_challenges")
    op.drop_index("ix_mfa_challenges_login_session_id", table_name="mfa_challenges")
    op.drop_index("ix_mfa_challenges_user_id", table_name="mfa_challenges")
    op.drop_table("mfa_challenges")
    op.create_index(
        op.f("ix_login_sessions_login_method"),
        "login_sessions",
        ["login_method"],
        unique=False,
    )
    op.drop_index(
        "ix_passkey_backup_unused",
        table_name="passkey_backup_codes",
        postgresql_where="(used_at IS NULL)",
    )
    op.drop_index("ix_passkey_backup_user", table_name="passkey_backup_codes")
    op.drop_index(
        "ix_passkey_active",
        table_name="passkey_credentials",
        postgresql_where="(revoked_at IS NULL)",
    )
    op.drop_index("ix_passkey_credential_id", table_name="passkey_credentials")
    op.drop_index("ix_passkey_revoked_at", table_name="passkey_credentials")
    op.drop_index("ix_passkey_user_id", table_name="passkey_credentials")
    op.drop_index(
        "ix_change_requests_created_at", table_name="subsystem_change_requests"
    )
    op.drop_index(
        "ix_change_requests_requested_by", table_name="subsystem_change_requests"
    )
    op.drop_index("ix_change_requests_status", table_name="subsystem_change_requests")
    op.drop_index(
        "ix_change_requests_subsystem", table_name="subsystem_change_requests"
    )
    op.drop_index("ix_change_requests_type", table_name="subsystem_change_requests")
    op.alter_column(
        "subsystems",
        "allowed_roles",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        type_=postgresql.ARRAY(sa.String()),
        existing_nullable=False,
        existing_server_default=sa.text("'{user}'::text[]"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subsystems",
        "allowed_roles",
        existing_type=postgresql.ARRAY(sa.String()),
        type_=postgresql.ARRAY(sa.TEXT()),
        existing_nullable=False,
        existing_server_default=sa.text("'{user}'::text[]"),
    )
    op.create_index(
        "ix_change_requests_type",
        "subsystem_change_requests",
        ["request_type"],
        unique=False,
    )
    op.create_index(
        "ix_change_requests_subsystem",
        "subsystem_change_requests",
        ["subsystem_id"],
        unique=False,
    )
    op.create_index(
        "ix_change_requests_status",
        "subsystem_change_requests",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_change_requests_requested_by",
        "subsystem_change_requests",
        ["requested_by"],
        unique=False,
    )
    op.create_index(
        "ix_change_requests_created_at",
        "subsystem_change_requests",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_passkey_user_id", "passkey_credentials", ["user_id"], unique=False
    )
    op.create_index(
        "ix_passkey_revoked_at", "passkey_credentials", ["revoked_at"], unique=False
    )
    op.create_index(
        "ix_passkey_credential_id",
        "passkey_credentials",
        ["credential_id"],
        unique=False,
    )
    op.create_index(
        "ix_passkey_active",
        "passkey_credentials",
        ["user_id"],
        unique=False,
        postgresql_where="(revoked_at IS NULL)",
    )
    op.create_index(
        "ix_passkey_backup_user", "passkey_backup_codes", ["user_id"], unique=False
    )
    op.create_index(
        "ix_passkey_backup_unused",
        "passkey_backup_codes",
        ["user_id"],
        unique=False,
        postgresql_where="(used_at IS NULL)",
    )
    op.drop_index(op.f("ix_login_sessions_login_method"), table_name="login_sessions")
    op.create_table(
        "mfa_challenges",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("login_session_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "code_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column("method", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "used_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("attempts", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["login_session_id"],
            ["login_sessions.id"],
            name="mfa_challenges_login_session_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="mfa_challenges_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="mfa_challenges_pkey"),
    )
    op.create_index(
        "ix_mfa_challenges_user_id", "mfa_challenges", ["user_id"], unique=False
    )
    op.create_index(
        "ix_mfa_challenges_login_session_id",
        "mfa_challenges",
        ["login_session_id"],
        unique=False,
    )
    op.create_index(
        "ix_mfa_challenges_created_at", "mfa_challenges", ["created_at"], unique=False
    )
    # ### end Alembic commands ###
