#!/usr/bin/env bash
# create.sh — สร้าง git worktree + docker-compose.override.yml + ปรับ .env
# Usage: bash scripts/worktree/create.sh <slot> [<branch-suffix>]
#   slot: hub | dorm | library | ml
#   branch-suffix: ชื่อต่อท้าย feature/<slot>-<suffix>  (default: dev)
#
# ตัวอย่าง:
#   bash scripts/worktree/create.sh hub                  → branch feature/hub-dev
#   bash scripts/worktree/create.sh ml mfa-week9         → branch feature/ml-mfa-week9

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=slots.sh
source "$SCRIPT_DIR/slots.sh"

# --- args ---
SLUG=${1:-}
SUFFIX=${2:-dev}

if [ -z "$SLUG" ]; then
  cat <<EOF
Usage: bash scripts/worktree/create.sh <slot> [<branch-suffix>]
  slot: hub | dorm | library | ml
  branch-suffix: ต่อท้าย feature/<slot>-<suffix>  (default: dev)
EOF
  exit 1
fi

validate_slug "$SLUG"

REPO_ROOT=$(git rev-parse --show-toplevel)
TARGET=$(slot_dir "$SLUG")
BRANCH="feature/${SLUG}-${SUFFIX}"
PROJECT=$(slot_project_name "$SLUG")
OFFSET=$(slot_offset "$SLUG")

read -r HUB_PORT DORM_PORT LIB_PORT PG_PORT PG_DORM_PORT PG_LIB_PORT REDIS_PORT ML_PORT \
  < <(slot_ports "$SLUG")

echo "==> Creating worktree for slot=$SLUG"
echo "    branch:  $BRANCH"
echo "    target:  $TARGET"
echo "    project: $PROJECT"
echo "    offset:  +$OFFSET"
echo

# --- 1. git worktree add ---
if [ -d "$TARGET" ]; then
  echo "WARN: $TARGET already exists — skipping git worktree add"
else
  if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
    echo "==> Branch $BRANCH already exists — reusing"
    git worktree add "$TARGET" "$BRANCH"
  else
    git worktree add "$TARGET" -b "$BRANCH" main
  fi
fi

# --- 2. generate docker-compose.override.yml ---
OVERRIDE="$TARGET/docker-compose.override.yml"
cat > "$OVERRIDE" <<EOF
# AUTO-GENERATED by scripts/worktree/create.sh — slot=$SLUG offset=+$OFFSET
# ถ้าต้องการเปลี่ยน port ลบไฟล์นี้แล้วรัน create.sh ใหม่
# ห้าม commit (อยู่ใน .gitignore)
# ports: !override = replace (ไม่ merge) กับ base docker-compose.yml
services:
  postgres:
    container_name: hub-postgres-$SLUG
    ports: !override
      - "$PG_PORT:5432"
  redis:
    container_name: hub-redis-$SLUG
    ports: !override
      - "$REDIS_PORT:6379"
  ml-service:
    container_name: hub-ml-$SLUG
    ports: !override
      - "$ML_PORT:9000"
  hub-backend:
    container_name: hub-backend-$SLUG
    ports: !override
      - "$HUB_PORT:8000"
  postgres-dorm:
    container_name: hub-postgres-dorm-$SLUG
    ports: !override
      - "$PG_DORM_PORT:5432"
  subsystem-dorm:
    container_name: hub-subsystem-dorm-$SLUG
    ports: !override
      - "$DORM_PORT:8000"
  postgres-library:
    container_name: hub-postgres-library-$SLUG
    ports: !override
      - "$PG_LIB_PORT:5432"
  subsystem-library:
    container_name: hub-subsystem-library-$SLUG
    ports: !override
      - "$LIB_PORT:8000"
EOF
echo "==> Wrote $OVERRIDE"

# --- 3. copy .env files ---
copy_env() {
  local src=$1 dst=$2
  if [ -f "$src" ] && [ ! -f "$dst" ]; then
    cp "$src" "$dst"
    echo "    copied .env: $dst"
  fi
}
copy_env "$REPO_ROOT/.env" "$TARGET/.env"
copy_env "$REPO_ROOT/hub/subsystem-dorm/.env" "$TARGET/hub/subsystem-dorm/.env"
copy_env "$REPO_ROOT/hub/subsystem-library/.env" "$TARGET/hub/subsystem-library/.env"

# --- 4. ปรับ HUB_BASE_URL/redirect URIs ใน .env ของ worktree ---
patch_env() {
  local file=$1 key=$2 value=$3
  if [ ! -f "$file" ]; then return; fi
  if grep -q "^${key}=" "$file"; then
    # sed -i works in Git Bash + Linux + macOS (BSD sed needs -i '')
    if sed --version >/dev/null 2>&1; then
      sed -i "s|^${key}=.*|${key}=${value}|" "$file"
    else
      sed -i '' "s|^${key}=.*|${key}=${value}|" "$file"
    fi
    echo "    patched $key in $file"
  else
    echo "${key}=${value}" >> "$file"
    echo "    appended $key to $file"
  fi
}

HUB_URL="http://localhost:$HUB_PORT"
patch_env "$TARGET/.env" "HUB_BASE_URL" "$HUB_URL"
patch_env "$TARGET/.env" "GOOGLE_REDIRECT_URI" "$HUB_URL/auth/google/callback"
patch_env "$TARGET/.env" "OAUTH_CALLBACK_URI" "$HUB_URL/oauth/callback"
patch_env "$TARGET/hub/subsystem-dorm/.env" "HUB_BASE_URL" "$HUB_URL"
patch_env "$TARGET/hub/subsystem-library/.env" "HUB_BASE_URL" "$HUB_URL"

# --- 5. symlink hub/backend/keys (shared JWT keys) ---
KEYS_SRC="$REPO_ROOT/hub/backend/keys"
KEYS_DST="$TARGET/hub/backend/keys"
if [ -d "$KEYS_SRC" ]; then
  if [ -e "$KEYS_DST" ] || [ -L "$KEYS_DST" ]; then
    echo "    keys link/dir already exists at $KEYS_DST"
  else
    if ln -s "$KEYS_SRC" "$KEYS_DST" 2>/dev/null; then
      echo "    symlinked keys → $KEYS_SRC"
    else
      cp -r "$KEYS_SRC" "$KEYS_DST"
      echo "    WARN: symlink failed (Windows ต้อง Developer Mode/admin) — copied แทน"
      echo "    หมายเหตุ: JWT key ใน worktree นี้แยกจาก main แล้ว — generate ใหม่ที่ใดที่หนึ่งเท่านั้น"
    fi
  fi
else
  echo "    WARN: $KEYS_SRC ไม่มี — รัน 'docker compose exec hub-backend python -m scripts.generate_jwt_keys' ที่ main ก่อน"
fi

# --- 6. pre-commit install (ถ้ามี) ---
if [ -f "$REPO_ROOT/.pre-commit-config.yaml" ] && command -v pre-commit >/dev/null 2>&1; then
  (cd "$TARGET" && pre-commit install >/dev/null 2>&1) && echo "    pre-commit installed in worktree"
fi

# --- 7. สรุป ---
echo
echo "==> เสร็จ! ขั้นถัดไป:"
echo
slot_summary "$SLUG"
echo
echo "  cd $TARGET"
echo "  bash $SCRIPT_DIR/up.sh         # start docker stack"
echo "  bash $SCRIPT_DIR/down.sh       # stop"
echo "  bash $SCRIPT_DIR/remove.sh $SLUG  # cleanup (ลบ volume + worktree + branch)"
echo
echo "อย่าลืม:"
echo "  - เพิ่ม redirect URI ใน Google Console:"
echo "      $HUB_URL/auth/google/callback"
echo "      $HUB_URL/oauth/callback"
echo
echo "==> เปิด Claude Code ใน worktree นี้แล้วพูดว่า:"
case "$SLUG" in
  hub)     echo "      /hub-backend       ← Hub FastAPI context" ;;
  dorm)    echo "      /subsystem-dorm    ← Subsystem A context" ;;
  library) echo "      /subsystem-library ← Subsystem B context" ;;
  ml)      echo "      /ml-service        ← ML Verifier context" ;;
  *)       echo "      /hub-backend       ← default Hub context" ;;
esac
